# Generated by Django 5.2.8 on 2025-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('monthly', 'Pro Monthly'), ('annual', 'Pro Annual')], max_length=50, unique=True),
        ),
    ]
