# Generated by Django 5.2.6 on 2025-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_icon_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='english_text',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='french_text',
        ),
        migrations.AddField(
            model_name='phrase',
            name='translated_text',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
