# Generated by Django 5.2.6 on 2025-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
