# Generated by Django 5.2.6 on 2025-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_token_otp_alter_token_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default_profile.png', upload_to='profile_images/'),
        ),
    ]
