# Generated by Django 5.2.6 on 2025-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
