# Generated by Django 5.2.6 on 2025-11-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_token_otp_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
